name: Deploy to Okteto

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Okteto CLI
        run: curl https://get.okteto.com -sSfL | sh

      - name: Login to Okteto
        env:
          OKTETO_TOKEN: ${{ secrets.OKTETO_TOKEN }}
        run: okteto login --token $OKTETO_TOKEN

      - name: Deploy to Okteto
        env:
          MODEL_NAME: api
          NODO: 1
          DOCKER_USER: irvingrcm123
        run: |
          sed -i 's/{model_name}/'"${MODEL_NAME}"'/g' manifests/k8s.yaml
          sed -i 's/{nodo}/'"${NODO}"'/g' manifests/k8s.yaml
          sed -i 's/{docker_user}/'"${DOCKER_USER}"'/g' manifests/k8s.yaml
          sed -i 's/{github.sha}/'"${{ github.sha }}"'/g' manifests/k8s.yaml
          okteto up -f manifests/k8s.yaml
